# See the following discussions for the reason behind the JVM properties in the Store entrypoint:
#   see: https://github.com/localstack/localstack/issues/1037
#   see: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/SkipMd5CheckStrategy.java#L32-L42

version: '3.7'

services:
  store:
    image: cnxta/ion-store
    entrypoint:
      - java
      - -Dcom.amazonaws.services.s3.disablePutObjectMD5Validation=true
      - -Dcom.amazonaws.services.s3.disableGetObjectMD5Validation=true
      - -jar
      - /store
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack:0.10.5
    ports:
      - 4572:4572
      - 8055:8080
    volumes:
      - ./deployments/local/scripts:/docker-entrypoint-initaws.d
      - ./.localstack:/tmp/localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      - cdr
configs:
  # Directories are relative to the master compose file
  s3_config:
    file: deployments/local/configs/s3_config.yml
  store_config:
    file: deployments/local/configs/store_config.yml