# Local deployment config file
endpointUrl:
  store: http://cdr-store:9041/store/
  retrieve: http://cdr-ingest:9040/retrieve/
  transform: http://localhost:9090/transform/
logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG