version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2019-06-19T18-24-42Z
    entrypoint: sh
    hostname: minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=miniokey
      - MINIO_SECRET_KEY=miniokey
    networks:
      - cdr-local
    command: -c "mkdir /data/ingest-quarantine && /usr/bin/minio server /data"

networks:
  cdr-local:
    external: true

secrets:
  aws_s3_secret:
    file: deployments/local-minio/minio_secret.notsec
  aws_s3_access:
    file: deployments/local-minio/minio_access.notsec

configs:
  ingest_config:
    file: deployments/local-minio/ingest_config.yml
  mis_config:
    file: deployments/local-minio/mis_config.yml
