version: '3.7'
services:
  store:
    image: ${REGISTRY:-docker.io}/cnxta/ion-store
    ports:
      - target: 8080
        published: 9041
        protocol: tcp
      - target: 10051
        published: 10051
        protocol: tcp
    networks:
      - cdr
    deploy:
      restart_policy:
        condition: any
    secrets:
      - source: s3_secret
        target: /secrets/store/s3_secret.sec
      - source: s3_access
        target: /secrets/store/s3_access.sec
    configs:
      - source: s3_config
        target: /configs/s3_config.yml
      - source: store_config
        target: /configs/store_config.yml
    command:
      - "--s3.secret.file=/secrets/store/s3_secret.sec"
      - "--s3.access.file=/secrets/store/s3_access.sec"
      - "--spring.config.additional-location=file:/configs/s3_config.yml"
      - "--spring.config.additional-location=file:/configs/store_config.yml"
networks:
  cdr:
    external: true
secrets:
  s3_secret:
    file: s3_secret.sec
  s3_access:
    file: s3_access.sec
configs:
  s3_config:
    file: ./configs/s3_config.yml
  store_config:
    file: ./configs/store_config.yml