version: '3.7'
services:
  ingest:
    image: ${REGISTRY:-docker.io}/cnxta/cdr-ingest:0.1.0-SNAPSHOT
    hostname: cdr-ingest
    ports:
      - target: 8080
        published: 9040
        protocol: tcp
    networks:
      - cdr
    deploy:
      restart_policy:
        condition: any
  multi-int-store:
    image: ${REGISTRY:-docker.io}/cnxta/cdr-multi-int-store:0.1.0-SNAPSHOT
    hostname: cdr-store
    ports:
      - target: 8080
        published: 9041
        protocol: tcp
    restart: on-failure
    networks:
      - cdr
    depends_on:
      - cassandra
      - solr
    deploy:
      restart_policy:
        condition: any
    command:
      - "--cassandra.host=cassandra"
      - "--cassandra.port=9042"
      - "--solr.host=solr"
      - "--solr.port=9983"
  search:
    image: ${REGISTRY:-docker.io}/cnxta/cdr-search:0.1.0-SNAPSHOT
    hostname: cdr-search
    ports:
      - target: 8080
        published: 9039
        protocol: tcp
    networks:
      - cdr
    deploy:
      restart_policy:
        condition: any
  cassandra:
    image: cassandra
    hostname: cassandra
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
    networks:
      - cdr
  solr:
    image: solr
    hostname: solr
    ports:
      - target: 9983
        published: 9983
        protocol: tcp
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - searchTerms
    networks:
      - cdr
networks:
  cdr:
    external: true
volumes:
  data: