version: '3.7'
services:
  store:
    image: ${REGISTRY:-docker.io}/cnxta/ion-store:0.1.0-SNAPSHOT
    ports:
      - target: 8080
        published: 9043
        protocol: tcp
      - target: 10053
        published: 10053
        protocol: tcp
    networks:
      - cdr
    deploy:
      restart_policy:
        condition: any
    secrets:
      - source: aws_s3_secret
        target: /secrets/aws_s3_secret.sec
      - source: aws_s3_access
        target: /secrets/aws_s3_access.sec
    configs:
      - source: s3_config
        target: /configs/s3_config.yml
      - source: store_config
        target: /configs/store_config.yml
    command:
      - "--aws.s3.secret.file=/secrets/aws_s3_secret.sec"
      - "--aws.s3.access.file=/secrets/aws_s3_access.sec"
      - "--spring.config.additional-location=file:/configs/s3_config.yml"
      - "--spring.config.additional-location=file:/configs/store_config.yml"
networks:
  cdr:
    external: true
secrets:
  aws_s3_secret:
    file: aws_s3_secret.sec
  aws_s3_access:
    file: aws_s3_access.sec
configs:
  s3_config:
    file: ./configs/s3_config.yml
  store_config:
    file: ./configs/store_config.yml