version: '3.7'

services:
  minio:
    image: minio/minio
    entrypoint: sh
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=MINIOEXAMPLEACCESSKEY
      - MINIO_SECRET_KEY=MINIOEXAMPLESECRETKEY
    networks:
      - cdr
    command: -c "mkdir /data/ingest-quarantine && /usr/bin/minio server /data"
  # Enable JVM monitoring
  ingest:
    ports:
      - target: 10040
        published: 10040
        protocol: tcp
  store:
    ports:
      - target: 10041
        published: 10041
        protocol: tcp

secrets:
  # Directories are relative to the master compose file
  aws_s3_secret:
    file: deployments/local-minio/secrets/minio_secret.notsec
  aws_s3_access:
    file: deployments/local-minio/secrets/minio_access.notsec

configs:
  # Directories are relative to the master compose file
  ingest_config:
    file: deployments/local-minio/configs/ingest_config.yml
  transform_config:
    file: deployments/local-minio/configs/transform_config.yml
  mis_config:
    file: deployments/local-minio/configs/mis_config.yml