version: '3.7'

services:
  store:
    image: cnxta/ion-store
    depends_on:
      - minio
  minio:
    image: minio/minio
    entrypoint: sh
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=MINIOEXAMPLEACCESSKEY
      - MINIO_SECRET_KEY=MINIOEXAMPLESECRETKEY
    networks:
      - cdr
    command: -c "mkdir /data/ingest-quarantine && mkdir /data/irm && mkdir /data/metacard-quarantine && /usr/bin/minio server /data"
secrets:
  # Directories are relative to the master compose file
  s3_secret:
    file: deployments/local-minio/secrets/minio_secret.notsec
  s3_access:
    file: deployments/local-minio/secrets/minio_access.notsec
configs:
  # Directories are relative to the master compose file
  s3_config:
    file: deployments/local-minio/configs/s3_config.yml
  store_config:
    file: deployments/local-minio/configs/store_config.yml