logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "/actuator"

spring:
  profiles:
    active: s3Production,solrProduction