logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: production
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 11GB

# The index endpoint should be deployed in the same network, so we don't need a config.yml file for it.
endpointUrl:
  index: http://search:8080/index/

endpoints:
  transform:
    version: ${transformApiVersion}
  index:
    version: ${indexApiVersion}
  store:
    version: ${storeApiVersion}
