#Base CircleCI template for Gradle projects.
#Defined below are steps for building, OWasp, and Sonar

version: 2.1
executors:
  job-executor:
    docker:
      - image: circleci/openjdk:11-jdk
jobs:
  build:
    executor: job-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building
          command: |
            ./gradlew build --info
      - persist_to_workspace:
          root: ~/project
          paths:
            - build/classes
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/builds/reports/tests/test/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  #Runs OWASP on build
  owasp:
    executor: job-executor
    steps:
      - checkout
      - run:
          name: Owasp Tests
          command: |
            ./gradlew dependencyCheckAnalyze --info
  #Runs SonarQube on build
  sonar:
    executor: job-executor
    parameters:
      sonar_key:
        type: string
      sonar_org:
        type: string
      sonar_url:
        type: string
      sonar_token:
        type: string
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Sonar check
          command: ./gradlew build sonarqube -Dsonar.projectKey=<<parameters.sonar_key>> -Dsonar.organization=<<parameters.sonar_org>> -Dsonar.host.url=<<parameters.sonar_url>> -Dsonar.login=<<parameters.sonar_token>> -Dsonar.pullrequest.key=${CIRCLE_PULL_REQUEST##*/} -Dsonar.pullrequest.branch=${CIRCLE_BRANCH} -Dsonar.pullrequest.base=master
workflows:
  version: 2.1
  PR-Build:
    jobs:
#      - build
#      - owasp:
#          requires:
#            - build
      - sonar:
          context: secrets
#          requires:
#            - owasp
          sonar_key: ${CIRCLE_PROJECT_REPONAME}
          sonar_org: ${SONAR_ORG}
          sonar_url: https://sonarcloud.io
          sonar_token: ${SONAR_TOKEN}