swagger: "2.0"
info:
  description: "Internal Transform API"
  version: "1.0.0"
  title: "Internal Transform API"
schemes:
- "https"
- "http"
paths:
  /transform:
   post:
      summary: Transform request
      consumes:
        - application/json
      parameters:
        - in: body
          name: input
          description: The input to transform.
          schema:
            type: object
            required:
              - id
              - stagedLocation
              - productLocation
              - mimeType
              - bytes
              - callbackUrl
            properties:
              id:
                type: string
              stagedLocation:
                type: string
              productLocation:
                type: string
              mimeType:
                type: string
              bytes:
                type: number
              callbackUrl:
                type: string
      responses:
        202:
          description: Accepted
        400:
          description: Bad Request
        500:
          description: Internal Server Error
  #/mis/store:
  # post:
  #    summary: Callback URL with transformation status
  #    consumes:
  #      - application/json
  #    parameters:
  #      - in: body
  #        name: input
  #        description: The input to transform.
  #        schema:
  #          type: object
  #          required:
  #            - id
  #            - status
  #            - type
  #            - security
  #          properties:
  #            id:
  #              type: string
  #            status:
  #              type: string
  #            type:
  #              type: string
  #            mimeType:
  #              type: string
  #            bytes:
  #              type: number
  #            location:
  #              type: string
  #            security: 
  #              type: object
  #              properties:
  #                classification:
  #                  type: string
  #                ownerProducer:
  #                  type: string
  #    responses:
  #      200:
  #        description: OK
  #      400:
  #        description: Bad Request
  #      500:
  #        description: Internal Server Error
