aws:
  s3:
    endpointUrl: http://minio:9000
    region: local
    bucket:
      quarantine: ingest-quarantine
 
endpointUrl:
  transform: http://cdr-store:9041/transform/
  ingest:
    callback: http://cdr-store:9041/store/
    retrieve: http://cdr-ingest:9040/retrieve/