aws:
  s3:
    endpointUrl: http://minio:9000
    region: local
    bucket:
      quarantine: ingest-quarantine
solr:
  host: solr
  port: 8983
endpointUrl:
  retrieve: http://multi-int-store:9041/mis/product/