version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_reviewers:
      - "jhunzik"
      - "emmberk"
      - "ahoffer"