spring:
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 11GB
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.client: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
endpoints:
  transform:
    version: ${transformApiVersion}
